### ISSUE TITLE
infinite loop when empty regexp

### ISSUE THREAD

**Issue by ksss** [mattn/mruby-onig-regexp#50]
```rb
"hello".gsub(//, ".")
# Expect => ".h.e.l.l.o."
# Actual => infinite loop
```

See also https://github.com/ruby/spec/blob/0fe99d24f4a17eaa39563623209747eee278c3d1/core/string/gsub_spec.rb#L25

https://github.com/ruby/ruby/blob/745f4dd5b834a00f1cc201adb72ea3c8c8d4decb/string.c#L5005-L5006

**Comment by mattn** [comment]
strange! https://travis-ci.org/mattn/mruby-onig-regexp/builds/206859000

**Comment by ksss** [comment]
@mattn Thanks ✨
