### ISSUE TITLE
Support `Regexp#match?`

### ISSUE THREAD

**Issue by take-cheeze** [mattn/mruby-onig-regexp#81]
https://github.com/mruby/mruby/issues/3968

**Comment by mattn** [comment]
Is this you want?
https://github.com/mattn/mruby-onig-regexp/blob/71f0ff7c0dad04cc041bd650a6b29946b11d3dba/src/mruby_onig_regexp.c#L1101

**Comment by mattn** [comment]
Ah, `?`

**Comment by take-cheeze** [comment]
Seems like `String#match?` exists too. It's more lighter because it doesn't need to create `MatchData` object.

**Comment by mattn** [comment]
Yes, but must not update variables that have prefix `$`.

**Comment by mattn** [comment]
closed by https://github.com/mattn/mruby-onig-regexp/pull/82

**Comment by proyb6** [comment]
This additional meant match or match?

**Comment by mattn** [comment]
This is `match?`

**Comment by proyb6** [comment]
Appreciate!
