### ISSUE TITLE
Freeze regex variable

### ISSUE THREAD

**Issue by proyb6** [mattn/mruby-onig-regexp#83]
Is there a way to free regex in variable that should not be change through out lifetime? It appear I couldn't get the match working.

Working:
```
/^[A]{1}[0-9]{6}[A-Z]{1}$/.match?("A123456A".freeze) ? "" : res << {"IC" => "err1"}
```

Wanted:
```
ic = Regex.new("/^[A]{1}[0-9]{6}[A-Z]{1}$").freeze
```

**Comment by take-cheeze** [comment]
What do you want?:
- Do you want to freeze the regex object?
- Do you want to freeze the passed string object?

Regexp object is immutable currently so `OnigRegexp#freeze` should work.
