### ISSUE TITLE
Match? bug

### ISSUE THREAD

**Issue by proyb6** [mattn/mruby-onig-regexp#84]
Just discovered a bug when used in comparing against regex?

Did not match, should be match
```if /jpg/.match?(env["HTTP_ACCEPT"])```

Working, match as expected
```if /jpg/.match(env["HTTP_ACCEPT"])```

**Comment by take-cheeze** [comment]
You should paste what's in the `env["HTTP_ACCEPT"]` for test improvement.

**Comment by proyb6** [comment]
Sorry, added HTTP_ACCEPT
```
"HTTP_ACCEPT":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
```

I've tested ```webp``` which could not match.
```
if /webp/.match?(env["HTTP_ACCEPT"])
```
